apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: retail
  labels:
    app: checkout
data:
  ENDPOINTS_ORDERS: "http://orders.retail.svc.cluster.local"
  ENDPOINTS_CART: "http://cart.retail.svc.cluster.local"
  ENDPOINTS_CATALOG: "http://catalog.retail.svc.cluster.local"
  SERVER_PORT: "8080"
  # redis endpoint from terraform output
  REDIS_URL: "redis://ausmart-dev-redis.xxxxx.cache.amazonaws.com:6379"
