apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: retail
  labels:
    app: cart
data:
  CARTS_DYNAMODB_TABLENAME: "Items"
  CARTS_DYNAMODB_CREATETABLE: "false"
  AWS_DEFAULT_REGION: "ap-southeast-2"
  SERVER_PORT: "8080"
