apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: retail
  labels:
    app: ui
data:
  ENDPOINTS_CATALOG: "http://catalog.retail.svc.cluster.local"
  ENDPOINTS_CART: "http://cart.retail.svc.cluster.local"
  ENDPOINTS_CHECKOUT: "http://checkout.retail.svc.cluster.local"
  ENDPOINTS_ORDERS: "http://orders.retail.svc.cluster.local"
  SERVER_PORT: "8080"
