apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-db-secret-provider
  namespace: retail
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "ausmart-dev/rds/catalog-credentials"
        objectType: "secretsmanager"
